services:
  - type: web
    name: scholarmate_backend
    env: python
    rootDir: backend
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install --force-reinstall pydub==0.25.1
      pip install -r requirements.txt

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    build:
      pythonVersion: 3.11
      systemPackages:
        - ffmpeg

    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_NEW
        sync: false
      - key: GROQ_API_KEY_MCQ
        sync: false
      - key: GROQ_API_KEY_QA
        sync: false
