services:
  - type: web
    name: scholarmate-backend
    env: python
    pythonVersion: 3.11
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    systemPackages:
      - ffmpeg
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_NEW
        sync: false
      - key: GROQ_API_KEY_MCQ
        sync: false
      - key: GROQ_API_KEY_QA
        sync: false
